version: '3'

services:
  web:
    build: ./nova_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./nova_project:/code
      - ./migrations:/migrations
    environment:
      DATABASE: ./database.db
    ports:
      - "8000:8000"
